name: Trigger OnePlus Ace5 Docker Build

on:
  push:
    branches:
      - ReSukiSU
    paths:
      - '.github/workflows/trigger-oneplus-ace5-docker.yml'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Build Kernel workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Build Kernel OnePlus.yml',
              ref: 'ReSukiSU',
              inputs: {
                FILE: 'oneplus_ace5_b',
                DROID_SPACES: 'true',
                SCHED_HMBIRD: 'false'
              }
            })
